### ISSUE TITLE
Need to have GraphicsMagick installed

### ISSUE THREAD

**Issue by thomasmattheussen** [andismith/grunt-responsive-images#35]
Hi,

First off: great plugin :) thanks

Had some issue setting it up though...

I had ImageMagick already installed on my machine, so I set "engine": "im" being under the impression that I didn't need to have GraphicsMagick installed. 
But I got this error: "Please ensure ImageMagick is installed correctly" untill I ALSO installed GraphicsMagick. 

The documentation says "You need to install EITHER GraphicsMagick OR Imagemagick CLI tools".

Anyway, working great now ;)

**Comment by rpkoller** [comment]
@andismith hmmm that's odd i've pulled a grunt project onto my machine with grunt responsive images as dependency. i haven't had the need for installing imagemagick nor graphicsmagick so far . i am running grunt 0.4.5 as well as grunt responsive images 0.1.6 . i've installed the latest imagemagick version afterwards since the gruntfile listed imagemagick as engine. when i ran grunt i got: 

```
Running "responsive_images:logos" (responsive_images) task
>> spawn gm ENOENT
Warning: 
Please ensure ImageMagick is installed correctly.
`brew install imagemagick` or see http://www.imagemagick.org/script/binary-releases.php for more details.
Alternatively, set options.engine to 'gm' to use GraphicsMagick.
 Use --force to continue.
```
after that i've installed graphicsmagick too. as soon as the second formula was installed the grunt task worked. so it seems the previous fix is broken again :/

**Comment by emailtosamit** [comment]
This is giving following error to me:-

Warning:
Please ensure ImageMagick is installed correctly.
`brew install imagemagick` or see http://www.imagemagick.org/script/binary-relea
ses.php for more details.
Alternatively, set options.engine to 'gm' to use GraphicsMagick.
 Use --force to continue.

Aborted due to warnings.

**Comment by gooneraki** [comment]
@emailtosamit I had the same problem. I installed GraphicsMagick instead, set options.engine to 'gm' and it worked.
